# Generated by Django 4.0.4 on 2022-06-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proovedor',
            new_name='Proveedor',
        ),
    ]
