# Generated by Django 4.0.4 on 2022-06-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_proovedor_plato_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='proveedor',
            new_name='proovedor',
        ),
        migrations.AlterField(
            model_name='plato',
            name='miniatura',
            field=models.ImageField(upload_to=''),
        ),
    ]
