# Generated by Django 4.0.4 on 2022-07-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_proovedor_plato_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='miniatura',
            field=models.ImageField(null=True, upload_to='platos'),
        ),
    ]
