# Generated by Django 4.0.6 on 2022-07-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_remove_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.BooleanField(),
        ),
    ]
