# Generated by Django 4.0.6 on 2022-07-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
